// Copyright (c) 2013-2018 Rob Norris and Contributors
// This software is licensed under the MIT License (MIT).
// For more information see LICENSE or https://opensource.org/licenses/MIT

package doobie.tagless.jdbc

import java.io.InputStream
import java.io.Reader
import java.lang.Class
import java.lang.String
import java.math.BigDecimal
import java.net.URL
import java.sql.Blob
import java.sql.Clob
import java.sql.Date
import java.sql.NClob
import java.sql.Ref
import java.sql.ResultSet
import java.sql.ResultSetMetaData
import java.sql.RowId
import java.sql.SQLType
import java.sql.SQLWarning
import java.sql.SQLXML
import java.sql.Statement
import java.sql.Time
import java.sql.Timestamp
import java.sql.{ Array => SqlArray }
import java.util.Calendar
import java.util.Map

/** Algebra of operations for `java.sql.ResultSet`. */
@SuppressWarnings(Array("org.wartremover.warts.Overloading"))
trait JdbcResultSet[F[_]] {
  def absolute(a: Int): F[Boolean]
  def afterLast: F[Unit]
  def beforeFirst: F[Unit]
  def cancelRowUpdates: F[Unit]
  def clearWarnings: F[Unit]
  def close: F[Unit]
  def deleteRow: F[Unit]
  def findColumn(a: String): F[Int]
  def first: F[Boolean]
  def getArray(a: Int): F[SqlArray]
  def getArray(a: String): F[SqlArray]
  def getAsciiStream(a: Int): F[InputStream]
  def getAsciiStream(a: String): F[InputStream]
  def getBigDecimal(a: Int): F[BigDecimal]
  def getBigDecimal(a: Int, b: Int): F[BigDecimal]
  def getBigDecimal(a: String): F[BigDecimal]
  def getBigDecimal(a: String, b: Int): F[BigDecimal]
  def getBinaryStream(a: Int): F[InputStream]
  def getBinaryStream(a: String): F[InputStream]
  def getBlob(a: Int): F[Blob]
  def getBlob(a: String): F[Blob]
  def getBoolean(a: Int): F[Boolean]
  def getBoolean(a: String): F[Boolean]
  def getByte(a: Int): F[Byte]
  def getByte(a: String): F[Byte]
  def getBytes(a: Int): F[Array[Byte]]
  def getBytes(a: String): F[Array[Byte]]
  def getCharacterStream(a: Int): F[Reader]
  def getCharacterStream(a: String): F[Reader]
  def getClob(a: Int): F[Clob]
  def getClob(a: String): F[Clob]
  def getConcurrency: F[Int]
  def getCursorName: F[String]
  def getDate(a: Int): F[Date]
  def getDate(a: Int, b: Calendar): F[Date]
  def getDate(a: String): F[Date]
  def getDate(a: String, b: Calendar): F[Date]
  def getDouble(a: Int): F[Double]
  def getDouble(a: String): F[Double]
  def getFetchDirection: F[Int]
  def getFetchSize: F[Int]
  def getFloat(a: Int): F[Float]
  def getFloat(a: String): F[Float]
  def getHoldability: F[Int]
  def getInt(a: Int): F[Int]
  def getInt(a: String): F[Int]
  def getLong(a: Int): F[Long]
  def getLong(a: String): F[Long]
  def getMetaData: F[ResultSetMetaData]
  def getNCharacterStream(a: Int): F[Reader]
  def getNCharacterStream(a: String): F[Reader]
  def getNClob(a: Int): F[NClob]
  def getNClob(a: String): F[NClob]
  def getNString(a: Int): F[String]
  def getNString(a: String): F[String]
  def getObject(a: Int): F[AnyRef]
  def getObject[T](a: Int, b: Class[T]): F[T]
  def getObject(a: Int, b: Map[String, Class[_]]): F[AnyRef]
  def getObject(a: String): F[AnyRef]
  def getObject[T](a: String, b: Class[T]): F[T]
  def getObject(a: String, b: Map[String, Class[_]]): F[AnyRef]
  def getRef(a: Int): F[Ref]
  def getRef(a: String): F[Ref]
  def getRow: F[Int]
  def getRowId(a: Int): F[RowId]
  def getRowId(a: String): F[RowId]
  def getSQLXML(a: Int): F[SQLXML]
  def getSQLXML(a: String): F[SQLXML]
  def getShort(a: Int): F[Short]
  def getShort(a: String): F[Short]
  def getStatement: F[Statement]
  def getString(a: Int): F[String]
  def getString(a: String): F[String]
  def getTime(a: Int): F[Time]
  def getTime(a: Int, b: Calendar): F[Time]
  def getTime(a: String): F[Time]
  def getTime(a: String, b: Calendar): F[Time]
  def getTimestamp(a: Int): F[Timestamp]
  def getTimestamp(a: Int, b: Calendar): F[Timestamp]
  def getTimestamp(a: String): F[Timestamp]
  def getTimestamp(a: String, b: Calendar): F[Timestamp]
  def getType: F[Int]
  def getURL(a: Int): F[URL]
  def getURL(a: String): F[URL]
  def getUnicodeStream(a: Int): F[InputStream]
  def getUnicodeStream(a: String): F[InputStream]
  def getWarnings: F[SQLWarning]
  def insertRow: F[Unit]
  def isAfterLast: F[Boolean]
  def isBeforeFirst: F[Boolean]
  def isClosed: F[Boolean]
  def isFirst: F[Boolean]
  def isLast: F[Boolean]
  def isWrapperFor(a: Class[_]): F[Boolean]
  def last: F[Boolean]
  def moveToCurrentRow: F[Unit]
  def moveToInsertRow: F[Unit]
  def next: F[Boolean]
  def previous: F[Boolean]
  def refreshRow: F[Unit]
  def relative(a: Int): F[Boolean]
  def rowDeleted: F[Boolean]
  def rowInserted: F[Boolean]
  def rowUpdated: F[Boolean]
  def setFetchDirection(a: Int): F[Unit]
  def setFetchSize(a: Int): F[Unit]
  def unwrap[T](a: Class[T]): F[T]
  def updateArray(a: Int, b: SqlArray): F[Unit]
  def updateArray(a: String, b: SqlArray): F[Unit]
  def updateAsciiStream(a: Int, b: InputStream): F[Unit]
  def updateAsciiStream(a: Int, b: InputStream, c: Int): F[Unit]
  def updateAsciiStream(a: Int, b: InputStream, c: Long): F[Unit]
  def updateAsciiStream(a: String, b: InputStream): F[Unit]
  def updateAsciiStream(a: String, b: InputStream, c: Int): F[Unit]
  def updateAsciiStream(a: String, b: InputStream, c: Long): F[Unit]
  def updateBigDecimal(a: Int, b: BigDecimal): F[Unit]
  def updateBigDecimal(a: String, b: BigDecimal): F[Unit]
  def updateBinaryStream(a: Int, b: InputStream): F[Unit]
  def updateBinaryStream(a: Int, b: InputStream, c: Int): F[Unit]
  def updateBinaryStream(a: Int, b: InputStream, c: Long): F[Unit]
  def updateBinaryStream(a: String, b: InputStream): F[Unit]
  def updateBinaryStream(a: String, b: InputStream, c: Int): F[Unit]
  def updateBinaryStream(a: String, b: InputStream, c: Long): F[Unit]
  def updateBlob(a: Int, b: Blob): F[Unit]
  def updateBlob(a: Int, b: InputStream): F[Unit]
  def updateBlob(a: Int, b: InputStream, c: Long): F[Unit]
  def updateBlob(a: String, b: Blob): F[Unit]
  def updateBlob(a: String, b: InputStream): F[Unit]
  def updateBlob(a: String, b: InputStream, c: Long): F[Unit]
  def updateBoolean(a: Int, b: Boolean): F[Unit]
  def updateBoolean(a: String, b: Boolean): F[Unit]
  def updateByte(a: Int, b: Byte): F[Unit]
  def updateByte(a: String, b: Byte): F[Unit]
  def updateBytes(a: Int, b: Array[Byte]): F[Unit]
  def updateBytes(a: String, b: Array[Byte]): F[Unit]
  def updateCharacterStream(a: Int, b: Reader): F[Unit]
  def updateCharacterStream(a: Int, b: Reader, c: Int): F[Unit]
  def updateCharacterStream(a: Int, b: Reader, c: Long): F[Unit]
  def updateCharacterStream(a: String, b: Reader): F[Unit]
  def updateCharacterStream(a: String, b: Reader, c: Int): F[Unit]
  def updateCharacterStream(a: String, b: Reader, c: Long): F[Unit]
  def updateClob(a: Int, b: Clob): F[Unit]
  def updateClob(a: Int, b: Reader): F[Unit]
  def updateClob(a: Int, b: Reader, c: Long): F[Unit]
  def updateClob(a: String, b: Clob): F[Unit]
  def updateClob(a: String, b: Reader): F[Unit]
  def updateClob(a: String, b: Reader, c: Long): F[Unit]
  def updateDate(a: Int, b: Date): F[Unit]
  def updateDate(a: String, b: Date): F[Unit]
  def updateDouble(a: Int, b: Double): F[Unit]
  def updateDouble(a: String, b: Double): F[Unit]
  def updateFloat(a: Int, b: Float): F[Unit]
  def updateFloat(a: String, b: Float): F[Unit]
  def updateInt(a: Int, b: Int): F[Unit]
  def updateInt(a: String, b: Int): F[Unit]
  def updateLong(a: Int, b: Long): F[Unit]
  def updateLong(a: String, b: Long): F[Unit]
  def updateNCharacterStream(a: Int, b: Reader): F[Unit]
  def updateNCharacterStream(a: Int, b: Reader, c: Long): F[Unit]
  def updateNCharacterStream(a: String, b: Reader): F[Unit]
  def updateNCharacterStream(a: String, b: Reader, c: Long): F[Unit]
  def updateNClob(a: Int, b: NClob): F[Unit]
  def updateNClob(a: Int, b: Reader): F[Unit]
  def updateNClob(a: Int, b: Reader, c: Long): F[Unit]
  def updateNClob(a: String, b: NClob): F[Unit]
  def updateNClob(a: String, b: Reader): F[Unit]
  def updateNClob(a: String, b: Reader, c: Long): F[Unit]
  def updateNString(a: Int, b: String): F[Unit]
  def updateNString(a: String, b: String): F[Unit]
  def updateNull(a: Int): F[Unit]
  def updateNull(a: String): F[Unit]
  def updateObject(a: Int, b: AnyRef): F[Unit]
  def updateObject(a: Int, b: AnyRef, c: Int): F[Unit]
  def updateObject(a: Int, b: AnyRef, c: SQLType): F[Unit]
  def updateObject(a: Int, b: AnyRef, c: SQLType, d: Int): F[Unit]
  def updateObject(a: String, b: AnyRef): F[Unit]
  def updateObject(a: String, b: AnyRef, c: Int): F[Unit]
  def updateObject(a: String, b: AnyRef, c: SQLType): F[Unit]
  def updateObject(a: String, b: AnyRef, c: SQLType, d: Int): F[Unit]
  def updateRef(a: Int, b: Ref): F[Unit]
  def updateRef(a: String, b: Ref): F[Unit]
  def updateRow: F[Unit]
  def updateRowId(a: Int, b: RowId): F[Unit]
  def updateRowId(a: String, b: RowId): F[Unit]
  def updateSQLXML(a: Int, b: SQLXML): F[Unit]
  def updateSQLXML(a: String, b: SQLXML): F[Unit]
  def updateShort(a: Int, b: Short): F[Unit]
  def updateShort(a: String, b: Short): F[Unit]
  def updateString(a: Int, b: String): F[Unit]
  def updateString(a: String, b: String): F[Unit]
  def updateTime(a: Int, b: Time): F[Unit]
  def updateTime(a: String, b: Time): F[Unit]
  def updateTimestamp(a: Int, b: Timestamp): F[Unit]
  def updateTimestamp(a: String, b: Timestamp): F[Unit]
  def wasNull: F[Boolean]
}

